services:
  auth_db:
    image: postgres:17.4-alpine
    container_name: auth-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: ${TZ}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${AUTH_POSTGRES_EXTERNAL_PORT}:5432"
    expose:
      - "5432"
    networks:
      - auth-network
  auth_redis:
    image: redis:7.4.2-alpine
    container_name: auth-redis
    restart: always
    env_file:
      - .env
    ports:
      - "${AUTH_REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - auth_redis_data:/data
    networks:
      - auth-network
    command: redis-server --appendonly yes --requirepass ${AUTH_REDIS_PASSWORD}
networks:
  auth-network:
    name: auth-network
    driver: bridge
volumes:
  postgres_data:
  auth_redis_data:
