services:
  user_db:
    image: postgres:17.4-alpine
    container_name: user-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: ${TZ}
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "${USER_POSTGRES_EXTERNAL_PORT}:${USER_POSTGRES_PORT}"
    expose:
      - "${USER_POSTGRES_PORT}"
    networks:
      - user-network